import { useState } from 'react'
import './App.css'

const places = [
  { id: 'jhu-library', name: 'George Peabody Library', area: 'Mount Vernon', type: 'Baltimore', points: 80, icon: '▦', color: 'gold', description: "A cathedral of books and one of Baltimore's most unforgettable rooms.", image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=900&q=85' },
  { id: 'charles-village', name: 'Black & Missing mural', area: 'Charles Village', type: 'Around campus', points: 40, icon: '✦', color: 'coral', description: 'Find the colorful rowhome blocks and the stories painted across them.', image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=900&q=85' },
  { id: 'jhu-hopkins', name: 'The Johns Hopkins Beach', area: 'Homewood', type: 'On campus', points: 20, icon: '⌁', color: 'blue', description: 'Stretch out on the grass and take the scenic shortcut through campus.', image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85' },
  { id: 'wyman-park', name: 'Wyman Park Dell', area: 'Charles Village', type: 'Around campus', points: 30, icon: '⌂', color: 'green', description: 'A leafy pocket for a walk, picnic, or reset between classes.', image: 'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=900&q=85' },
  { id: 'bma', name: 'Baltimore Museum of Art', area: 'Remington', type: 'Baltimore', points: 60, icon: '◈', color: 'purple', description: 'Meet Matisse, stroll the sculpture garden, and make an afternoon of it.', image: 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=900&q=85' },
  { id: 'union-wharf', name: 'Union Wharf', area: 'Fells Point', type: 'Baltimore', points: 100, icon: '≈', color: 'navy', description: 'Follow the harbor to cobblestones, small plates, and a different side of the city.', image: 'https://images.unsplash.com/photo-1509822929063-6b6cfc9b42f2?auto=format&fit=crop&w=900&q=85' },
]

const mapCoordinates = [[31, 31], [49, 40], [46, 22], [61, 33], [72, 55], [80, 76]]
const mapPlaces = places.map((place, index) => ({ ...place, x: mapCoordinates[index][0], y: mapCoordinates[index][1] }))
const ranks = ['Newbie', 'First Flight', 'Blue Jay', 'Campus Scout', 'City Walker', 'Local', 'Neighborhood Pro', 'Weekend Warrior', 'Charm City Guide', 'Baltimore Insider', 'Hunt Captain', 'Trailblazer', 'JHU Legend', 'City Connector', 'Local Legend']
const quests = [
  { id: 'campus-loop', title: 'The Homewood loop', detail: 'Visit three spots on campus', points: 75, icon: '◎', progress: 1, total: 3 },
  { id: 'art-day', title: 'Art in every direction', detail: 'Visit two art and culture spots', points: 90, icon: '◈', progress: 0, total: 2 },
  { id: 'city-lights', title: 'Chase the harbor', detail: 'Complete one Baltimore spot after 5 PM', points: 120, icon: '✦', progress: 0, total: 1 },
]

function App() {
  const [visited, setVisited] = useState([])
  const [filter, setFilter] = useState('All spots')
  const [search, setSearch] = useState('')
  const [selectedPlace, setSelectedPlace] = useState(mapPlaces[2])
  const [authOpen, setAuthOpen] = useState(false)
  const [authStep, setAuthStep] = useState('credentials')
  const [email, setEmail] = useState('')
  const [code, setCode] = useState('')
  const [loggedIn, setLoggedIn] = useState(false)
  const [authError, setAuthError] = useState('')
  const totalPoints = visited.reduce((sum, id) => sum + places.find((place) => place.id === id).points, 0)
  const rankIndex = Math.min(ranks.length - 1, Math.floor(totalPoints / 100))
  const currentRank = ranks[rankIndex]
  const nextRank = ranks[rankIndex + 1]
  const progress = nextRank ? ((totalPoints % 100) / 100) * 100 : 100
  const visiblePlaces = places.filter((place) => (filter === 'All spots' || place.type === filter) && `${place.name} ${place.area}`.toLowerCase().includes(search.toLowerCase()))

  function toggleVisited(id) { setVisited((current) => current.includes(id) ? current.filter((placeId) => placeId !== id) : [...current, id]) }
  function beginLogin(event) { event.preventDefault(); setAuthError(''); setAuthStep('verify') }
  function verifyCode(event) { event.preventDefault(); if (code === '123456') { setLoggedIn(true); setAuthOpen(false); setAuthStep('credentials'); setCode('') } else setAuthError('Use the demo verification code 123456.') }

  return (
    <div className="app-shell">
      <header className="topbar"><a className="brand" href="#top" aria-label="Hopkins Hunt home"><span className="brand-mark">HH</span><span>Hopkins Hunt</span></a><nav><a className="active" href="#recommendations">Explore</a><a href="#map">Map</a><a href="#quests">Quests</a><a href="#passport">Passport</a></nav><button className="profile-button" type="button" onClick={() => setAuthOpen(true)}><span className="profile-avatar">{loggedIn ? '✓' : '?'}</span>{loggedIn ? 'Verified JHU student' : 'Student login'}</button></header>
      <main id="top">
        <section className="dashboard-hero"><div><p className="eyebrow">JHU STUDENT ADVENTURE LOG</p><h1>Make the city<br /><em>your campus.</em></h1><p className="hero-description">Find your next Baltimore recommendation, complete student quests, and earn your way from Newbie to Local Legend.</p><div className="hero-actions"><a className="primary-button" href="#recommendations">Find a place <span>↓</span></a><button className="text-button" onClick={() => setAuthOpen(true)}>{loggedIn ? 'View verified pass' : 'Log in to save progress'} <span>→</span></button></div></div><div className="hero-score"><div className="score-orbit"><span className="orbit-dot"></span><strong>{totalPoints}</strong><small>POINTS</small></div><span className="score-rank">RANK {String(rankIndex + 1).padStart(2, '0')} / 15</span><b>{currentRank}</b><div className="score-progress"><span style={{ width: `${progress}%` }}></span></div><small>{nextRank ? `${100 - (totalPoints % 100)} pts to ${nextRank}` : 'Top rank unlocked'}</small></div></section>
        <section className="stat-strip"><div><span className="stat-label">VISITED</span><strong>{visited.length}<small> / {places.length}</small></strong><span>places explored</span></div><div><span className="stat-label">CURRENT RANK</span><strong>{currentRank}</strong><span>level {rankIndex + 1} of 15</span></div><div><span className="stat-label">J-CARD STATUS</span><strong className={loggedIn ? 'status-on' : ''}>{loggedIn ? 'Verified' : 'Unverified'}</strong><span>{loggedIn ? 'identity confirmed' : 'log in to activate'}</span></div></section>
        <section className="recommendations-section" id="recommendations"><div className="section-heading"><div><p className="eyebrow">01 / RECOMMENDATIONS</p><h2>Worth the walk.<br /><em>Worth the points.</em></h2></div><p className="section-note">Points change by location and difficulty.<br />The farther you roam, the faster you rise.</p></div><div className="controls"><div className="filter-tabs">{['All spots', 'On campus', 'Around campus', 'Baltimore'].map((tab) => <button key={tab} type="button" className={filter === tab ? 'selected' : ''} onClick={() => setFilter(tab)}>{tab}</button>)}</div><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search spots" /></label></div><div className="place-grid">{visiblePlaces.map((place) => { const isVisited = visited.includes(place.id); return <article className={`place-card ${isVisited ? 'visited' : ''}`} key={place.id}><div className="place-image" style={{ backgroundImage: `url(${place.image})` }}><span className={`place-icon ${place.color}`}>{place.icon}</span><span className="points">+{place.points} pts</span>{isVisited && <span className="visited-stamp">Visited ✓</span>}</div><div className="place-content"><div className="place-meta"><span>{place.type}</span><span>{place.area}</span></div><h3>{place.name}</h3><p>{place.description}</p><button className={`visit-button ${isVisited ? 'done' : ''}`} type="button" onClick={() => toggleVisited(place.id)}>{isVisited ? 'Added to passport' : 'Mark as visited'} <span>{isVisited ? '✓' : '+'}</span></button></div></article> })}</div></section>
        <section className="map-section" id="map"><div className="section-heading"><div><p className="eyebrow">02 / FIELD MAP</p><h2>One campus.<br /><em>Many directions.</em></h2></div><p className="section-note">Tap a pin to preview a destination.<br />Every route is worth taking.</p></div><div className="map-layout"><div className="campus-map"><div className="map-water"></div><div className="map-road road-one"></div><div className="map-road road-two"></div><span className="map-label homewood">HOMEWOOD</span><span className="map-label baltimore">BALTIMORE</span>{mapPlaces.map((place) => <button className={`map-pin ${selectedPlace.id === place.id ? 'selected' : ''}`} style={{ left: `${place.x}%`, top: `${place.y}%` }} key={place.id} onClick={() => setSelectedPlace(place)} aria-label={`Show ${place.name}`}>{place.icon}</button>)}</div><aside className="map-detail"><span className="detail-kicker">SELECTED DESTINATION</span><div className={`detail-icon ${selectedPlace.color}`}>{selectedPlace.icon}</div><h3>{selectedPlace.name}</h3><p>{selectedPlace.description}</p><div className="detail-row"><span>{selectedPlace.area}</span><strong>+{selectedPlace.points} pts</strong></div><button className="map-action" onClick={() => toggleVisited(selectedPlace.id)}>{visited.includes(selectedPlace.id) ? 'Saved to passport ✓' : 'Add destination'} <span>→</span></button></aside></div></section>
        <section className="quests-section" id="quests"><div className="section-heading"><div><p className="eyebrow">03 / STUDENT QUESTS</p><h2>Plans for your<br /><em>next free hour.</em></h2></div><span className="quest-count">{quests.length} active quests</span></div><div className="quest-grid">{quests.map((quest) => <article className="quest-card" key={quest.id}><div className="quest-number">{quest.icon}<span>QUEST</span></div><div className="quest-main"><h3>{quest.title}</h3><p>{quest.detail}</p><div className="quest-track"><span style={{ width: `${(quest.progress / quest.total) * 100}%` }}></span></div><small>{quest.progress} / {quest.total} complete</small></div><div className="quest-points">+{quest.points}<span>PTS</span></div></article>)}</div></section>
        <section className="passport-section" id="passport"><div className="passport-card"><div className="passport-top"><span className="passport-kicker">JOHNS HOPKINS UNIVERSITY</span><span className="passport-mark">HH</span></div><div className="passport-middle"><div><span className="passport-label">DIGITAL J-CARD PASS</span><h2>{loggedIn ? "Sofia's Hunt Pass" : 'Your Hunt Pass'}</h2><p>{loggedIn ? 'Verified student identity / active' : 'Log in to claim your verified student identity'}</p></div><div className={`verification-seal ${loggedIn ? 'verified' : ''}`}>{loggedIn ? '✓' : '?'}</div></div><div className="passport-bottom"><span>{loggedIn ? 'VERIFIED JHU STUDENT' : 'AWAITING VERIFICATION'}</span><span>{visited.length} STAMPS / {totalPoints} PTS</span></div></div><div className="passport-copy"><p className="eyebrow">04 / TRAVEL PASSPORT</p><h2>Keep your<br /><em>story moving.</em></h2><p>Your passport collects every spot you visit and gives your future profile a home. Login makes it portable across devices.</p><button className="primary-button" onClick={() => setAuthOpen(true)}>{loggedIn ? 'View account' : 'Login & verify'} <span>→</span></button></div></section>
      </main>
      <footer><span className="brand-mark">HH</span><span>Made for the curious Blue Jay.</span><span className="footer-right">Hopkins Hunt <i>✦</i></span></footer>
      {authOpen && <div className="modal-backdrop"><section className="auth-modal" role="dialog" aria-modal="true" aria-labelledby="auth-title"><button className="modal-close" onClick={() => setAuthOpen(false)} aria-label="Close login">×</button>{authStep === 'credentials' ? <form onSubmit={beginLogin}><span className="modal-mark">HH</span><p className="eyebrow">SECURE STUDENT ACCESS</p><h2 id="auth-title">Sign in to<br /><em>your hunt.</em></h2><p className="modal-copy">Use your Hopkins email to save points, unlock your J-Card pass, and keep your passport with you.</p><label>Hopkins email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@jh.edu" /></label><label>Password<input type="password" required minLength="4" placeholder="••••••••" /></label><button className="modal-submit" type="submit">Continue to verification <span>→</span></button><small className="demo-note">Demo mode: any Hopkins email works.</small></form> : <form onSubmit={verifyCode}><span className="modal-mark">02</span><p className="eyebrow">SECOND-FACTOR VERIFICATION</p><h2 id="auth-title">Check your<br /><em>device.</em></h2><p className="modal-copy">Enter the six-digit code sent to your verified Hopkins device. This demo uses a safe local placeholder.</p><label>Verification code<input className="code-input" inputMode="numeric" maxLength="6" required value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} placeholder="123456" /></label>{authError && <p className="auth-error">{authError}</p>}<button className="modal-submit" type="submit">Verify identity <span>✓</span></button><button className="back-button" type="button" onClick={() => setAuthStep('credentials')}>← Back to sign in</button></form>}</section></div>}
    </div>
  )
}

export default App
